name: Release Magic
on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      magic:
        description: 'Magic'
        required: true
  workflow_call:
    inputs:
      version:
        description: 'Version'
        type: string
        required: true
      magic:
        description: 'Magic'
        type: string
        required: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print Info
        run: |
          echo "COMMENT: ${{ env.COMMENT }}"
          echo GITHUB_REF: $GITHUB_REF
          echo "Event Inputs"
          echo "============"
          cat <<END_OF_JSON
          ${{ toJSON(github.event.inputs) }}
          END_OF_JSON
          echo "Workflow inputs"
          echo "==============="
          cat <<END_OF_JSON
          ${{ toJSON(inputs) }}
          END_OF_JSON
      - name: Release artifact
        run: |
          echo Releasing ${{ github.event.inputs.version || '2.4.2' }} with ${{ github.event.inputs.magic || 'more' }}
          echo Releasing ${{ inputs.version || '2.4.2' }} with ${{ inputs.magic || 'more' }}
        
